app/assets/stylesheets/shared/header.scss
=> Change header height from 64 to 48 and make touchups

Gemfile, Gemfile.lock, app/controllers/admins/semesters_controller.rb, app/models/app.rb, app/models/project.rb, app/models/semester.rb, app/views/admins/apps/index.html.erb, app/views/admins/semesters/_form.html.erb, app/views/admins/semesters/edit.html.erb, app/views/admins/semesters/index.html.erb, app/views/admins/semesters/new.html.erb, app/views/admins/semesters/show.html.erb, config/routes.rb, db/migrate/20150315214321_create_semesters.rb, db/migrate/20150316212014_add_semester_id_to_apps.rb, db/migrate/20150316212023_add_semester_id_to_projects.rb, db/migrate/20150316234146_remove_year_from_apps.rb, db/migrate/20150317010432_add_current_semester_column.rb, db/schema.rb, db/seeds.rb, spec/factories/apps.rb, spec/factories/semesters.rb, spec/features/semester_spec.rb, spec/models/app_spec.rb, spec/models/semester_spec.rb, spec/support/utilities.rb
=> Semester branch

app/assets/stylesheets/projects.scss
Animation is a bit awkward due to no footer still
=> Change height to fit content

app/assets/stylesheets/shared/header.scss, app/views/application/_header.html.erb
functional admin dropdown menu. i might have to work on making it look a lot better....
=> Add questionable Admin dropdown tab menu

app/assets/stylesheets/shared/header.scss
=> more bug fixes

app/assets/stylesheets/about.scss, app/controllers/pages_controller.rb, app/helpers/application_helper.rb, app/models/member.rb, app/models/member_role.rb, app/views/pages/about.html.erb
=> Add member names, gravatar, role to about page

app/views/layouts/application.html.erb
=> add favicon

app/assets/javascripts/vendor/toastr.js, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/vendor/toastr.css, app/views/application/_flash.html.erb, config/locales/en.yml
=> Add Toastr

app/assets/stylesheets/apply.scss, app/assets/stylesheets/vendor/base/_variables.scss, app/views/applicants/sessions/new.html.erb, app/views/applicants/shared/_links.html.erb, spec/features/student_application_spec.rb
=> student login page style

app/assets/stylesheets/vendor/base/_buttons.scss, app/views/nonprofits/passwords/new.html.erb
styling of forgot password page
=> styled forgot password page

app/views/projects/index.html.erb
=> fixed broken images

app/views/projects/index.html.erb
=> varuns face lol

config/environments/production.rb
Set up Cloudfront on the club's AWS account.
Closes #193
=> Use CDN for assets

app/models/nonprofit_application.rb, app/views/nonprofit_applications/new.html.slim, spec/features/new_nonprofit_application_spec.rb, spec/models/nonprofit_application_spec.rb
@SamLau95 @nishdesai this is ready!
=> Emergency npo application fix!

app/assets/javascripts/application.coffee, app/assets/javascripts/shared/google-analytics.coffee, app/assets/javascripts/shared/google-analytics.coffee.erb, app/views/application/_ga_boiler.html.slim, app/views/layouts/application.html.slim
=> Fix ga with turbolinks

config/environments/production.rb, config/environments/staging.rb
Don't merge until the CDN is done set up. Should be ok after 6/2/2015 onwards.
=> Different distributions for staging and production

app/controllers/pages_controller.rb, app/models/member_role.rb, db/members.yml, db/schema.rb, db/seeds.rb
Fix #202 
Need to update db with new member information.
=> Refactor member roles

app/views/application/_fb_meta_tags.html.slim, app/views/layouts/application.html.slim, app/views/projects/index.html.slim, spec/factories/auth.rb
=> Fix some https:// to be relative

app/controllers/student_applications_controller.rb, app/models/student_application.rb, app/views/apply/show.html.slim, app/views/apply/students.html.slim, app/views/student_applications/new.html.slim, config/locales/en.yml, db/migrate/20150825192509_add_columns_to_student_applications.rb, db/schema.rb, spec/factories/student_applications.rb
=> Howard: Open student apps

app/assets/javascripts/shared/google-analytics.coffee.erb
Cause i saw this in the console.
=> Remove extraneous consoles

db/members.yml, db/seeds.rb, lib/tasks/update.rake
- I fixed logic to update members in the seeds file because it created duplicates.
- I then took it out to make it a rake task so we can run it independently from the seeds
- I removed emails from members.yml since they would create duplicates
Go into the repo and run 
```
heroku run rake update:members
```
1. Add yourself to the members.yml
- If you want your gravitar image you have two options.  If you want your email public just add your email to the members.yml.  If you want to hide it add all your info except email and run
```
heroku run rails c
```
Then find your Member instance and update your email.
=> Howard: Update positions

db/members.yml
Since I'm above the law I will self merge
=> More members

data/members.yml, db/schema.rb
Added a few more members here!
=> Howard: More members

app/assets/javascripts/pages/nonprofit_application/cs169_disclaimer.coffee, app/controllers/nonprofit_applications_controller.rb, app/models/nonprofit_application.rb, app/views/nonprofit_applications/new.html.slim, config/locales/simple_form.en.yml, db/migrate/20160610035215_add_cs169_columns_to_application.rb, db/schema.rb, spec/factories/nonprofit_applications.rb, spec/features/new_nonprofit_application_spec.rb, spec/models/nonprofit_application_spec.rb
Adds extra fields and questions. The "client" question only shows up after cs169 is checked. Nothing else special.
=> Add extra fields to project application

Gemfile.lock, app/assets/stylesheets/admin.css.scss, app/assets/stylesheets/admin/nonprofit_applications/table.scss, app/assets/stylesheets/shared/tables.scss, app/models/nonprofit_application.rb, app/models/settings.rb, app/views/admins/nonprofit_applications/index.html.slim, db/seeds.rb, spec/factories/nonprofit_applications.rb, spec/factories/settings.rb, spec/models/nonprofit_application_spec.rb, spec/models/settings_spec.rb
@vivek @amillman
This PR makes the NPO app table look nicer on the admin side. Namely, the table itself and the Summary column is as wide as possible.
=> Fix up NPO app table styles

Gemfile, Gemfile.lock, app/views/admins/comparisons/new.html.slim, app/views/admins/student_applications/show.html.slim
=> Use autolinker to automatically add links

app/controllers/admins/comparisons_controller.rb, app/models/admin.rb, config/locales/en/admin.yml
Cap the number of comparisons and allow only super_admin comparisons at the end
=> Cap comparisons and allow only super_admins at the end

config/locales/en/apply/student.yml
Let me know if there are more changes needed to opening apps.
=> changed text on student application page

Dockerfile, config/database.yml.docker, docker-compose.yml, docker_setup.sh
Use docker and docker-compose to build development environment easily
@SaladRaider @jonmchu 
Maybe we can spread this to other projects.
=> Add docker scripts to launch development environment in Docker

app/controllers/admins/external_applications_controller.rb, app/views/application/_footer.html.slim, app/views/external_applications/new.html.slim
* Changes footer Blueprint to blueprint 
* Filters external applications by current semester
=> Adds back design experience field

app/assets/stylesheets/pages/about.scss, app/views/pages/about.html.slim, config/locales/en/about.yml
@eric-ls feel free to change in a later PR as you see fit, I'll merge this in first tmrw to give to vivian
=> Adds new section for expansion

Gemfile, Gemfile.lock, app/assets/javascripts/admin.coffee, app/assets/stylesheets/components/_navbar.scss, app/controllers/admins/settings_controller.rb, app/views/admins/settings/edit.html.slim, app/views/application/_navbar.html.slim, app/views/layouts/application.html.slim, config/initializers/assets.rb, db/migrate/20180710033449_add_notify_bar_to_settings.rb, db/schema.rb
=> Add notification bar with admin settings and header component

app/controllers/external_applications_controller.rb, app/controllers/student_applications_controller.rb, app/models/external_application.rb, app/models/student_application.rb, app/views/external_applications/new.html.slim, app/views/student_applications/new.html.slim, config/locales/en/external_application.yml, config/locales/en/student_application.yml, db/migrate/20180824061909_add_hardest_achievement_to_student_applications.rb, db/migrate/20180824064048_add_short_fields_to_student_applications.rb, db/migrate/20180824153707_add_outreach_position_to_external_applications.rb, db/schema.rb
=> Update student dev application questions copy for Fall 2018

config/locales/en/members.yml
=> Update members.yml for Fall 2018

config/locales/en/members.yml
=> add member information

app/views/nonprofit_applications/index.html.slim
Reverts calblueprint/calblueprint.org#319
Don't need this anymore
=> Revert "Comment out Interest Form disabling temporarily"

Procfile, app/assets/stylesheets/apply/apply.scss, app/assets/stylesheets/apply/new_application.scss, app/models/external_application.rb, app/models/question.rb, app/views/apply/students.html.slim, app/views/external_applications/new.html.slim, app/views/questions/_attachment.html.slim, app/views/questions/_checkbox.html.slim, app/views/questions/_long_text.html.slim, app/views/questions/_multiple_choice_radio.html.slim, app/views/questions/_short_text.html.slim, app/views/student_applications/new.html.slim, config/locales/en/apply/student.yml, config/locales/en/external_application.yml, db/seeds/applications.yml, db/seeds/questions.yml, lib/tasks/students.rake
Comparisons aren't working in this branch. @kevintli to handle that separately
=> Application updates for Fall 2019

.gitignore, app/views/application/_footer.html.slim, config/initializers/ensure_semester_and_settings_present.rb, config/locales/en/members.yml
* Update Noah's email address
* Update Fred's info
* Add TODO comment about initializer
* Add `vendor/bundle` to gitignore
=> Add comments and update members errors

app/assets/stylesheets/pages/about.scss, app/views/pages/about.html.slim, config/locales/en/about.yml
updated values based on constitution @loischang
=> louis wanted this

app/assets/stylesheets/apply/apply.scss, app/controllers/admins/settings_controller.rb, app/controllers/student_applications_controller.rb, app/models/admin.rb, app/models/settings.rb, app/models/social_media_urls.rb, app/views/admins/settings/edit.html.slim, app/views/admins/settings/show.html.slim, app/views/apply/students.html.slim, app/views/student_applications/new.html.slim, config/initializers/ensure_semester_and_settings_present.rb, config/locales/en/apply/student.yml, db/migrate/20190907222638_add_current_category_to_student_applications.rb, db/migrate/20200112024543_add_designer_app_open_to_settings.rb, db/schema.rb, db/seeds.rb, db/seeds/applications.yml, db/seeds/questions.yml, spec/factories/admins.rb, spec/factories/settings.rb, spec/features/admin/settings_spec.rb, spec/models/admin_spec.rb, spec/models/settings_spec.rb
* Add a designer app toggle to Settings
* Fix Settings initializer
=> Adding designer app toggle

Procfile, app/assets/stylesheets/apply/new_application.scss, app/controllers/admins/demographic_surveys_controller.rb, app/controllers/demographic_surveys_controller.rb, app/models/demographic_survey.rb, app/models/ethnicity.rb, app/views/admins/demographic_surveys/index.html.slim, app/views/demographic_surveys/new.html.slim, db/migrate/20200121023017_create_demographic_surveys.rb, db/migrate/20200121195128_create_ethnicities.rb, db/migrate/20200121195221_create_join_table_demographic_survey_ethnicity.rb, db/schema.rb, db/seeds/ethnicities.yml, db/seeds/questions.yml, lib/tasks/db_seed_ethnicities.rake, spec/models/ethnicity_spec.rb
Change race group to include all ethnicities
Make bp games question in dev app required
=> Add all ethnicities

app/models/external_application.rb, app/views/external_applications/new.html.slim, config/locales/en/external_application.yml, config/locales/en/members.yml
* Updated member list with current positions
* Fix external app to make design portfolio highly encouraged for director of marketing
=> Update members and external app

Procfile, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/apply/new_application.scss, app/assets/stylesheets/components/_navbar.scss, app/views/application/_navbar.html.slim, app/views/application/_notify-bar.html.slim, app/views/apply/students.html.slim, app/views/demographic_surveys/new.html.slim, app/views/external_applications/new.html.slim, app/views/layouts/application.html.slim, app/views/pages/home.html.slim, config/locales/en/members.yml, lib/tasks/db_seed_ethnicities.rake
* Updated Procfile from seeding ethnicities every deployment
* Fixed small and overlapping notify bar
* Removed skip button from demographic survey
* Minor styling changes to buttons
=> Fix notify bar and remove seeding ethnicities every deployment

app/models/student_application.rb, app/views/student_applications/new.html.slim, db/seeds/applications.yml, db/seeds/questions.yml, lib/tasks/students.rake
* Added available for Build with Blueprint question for students
* Fix student sync for when response is nil for a question
=> Add available for bwbp question and fix nil condition for student sync

lib/tasks/demographics.rake, lib/tasks/external.rake
* Updated External app syncing to Airtabe for Spring 2020
* Added demographic surveys syncing to Airtable
=> Update external sync and add demographics sync

app/controllers/external_applications_controller.rb, app/decorators/external_application_decorator.rb, app/models/demographic_survey.rb, app/models/ethnicity.rb, app/models/external_application.rb, app/views/external_applications/new.html.slim, app/views/student_applications/new.html.slim, config/locales/en/apply/student.yml, config/locales/en/external_application.yml, db/migrate/20200126005817_add_meet_the_club_question_to_external_application.rb, db/schema.rb, db/seeds/applications.yml, db/seeds/questions.yml, lib/tasks/external.rake, lib/tasks/students.rake, spec/models/demographic_survey_spec.rb, spec/models/ethnicity_spec.rb, spec/models/external_application_spec.rb
* Add Meet the Club question to student and external applications
* Fix typo on apply page
=> Add Meet the Club question and minor fixes

app/controllers/admins/comparisons_controller.rb, app/controllers/admins/settings_controller.rb, app/views/admins/settings/edit.html.slim, app/views/admins/settings/show.html.slim, app/views/admins/student_applications/index.html.slim, app/views/application/_notify-bar.html.slim, config/locales/en/admin.yml, db/migrate/20200201163737_add_notify_bar_admins_only_to_settings.rb, db/schema.rb, db/seeds/categories.yml, lib/tasks/demographics.rake, lib/tasks/students_comparison.rake, spec/models/student_application_spec.rb
* Remove application type question
* Updated comparison categories
* Added notify bar for admins only
=> Get ready for comparisonsssssss!!!!!

config/locales/en/members.yml
=> Update member list with SP20 new mems

config/locales/en/members.yml
* Changed `members.yml` to spell Sydney's name right
=> Fix Sydney's name

app/controllers/concerns/send_nonprofit_interest_form_email.rb, app/controllers/nonprofit_interest_forms_controller.rb, app/jobs/nonprofit_interest_form_mailer_job.rb, app/mailers/nonprofit_interest_form_mailer.rb, app/models/nonprofit_interest_form.rb, app/views/nonprofit_interest_form_mailer/email.html.slim, app/views/nonprofit_interest_form_mailer/email.text.slim, app/views/nonprofit_interest_forms/new.html.slim, config/locales/en/nonprofit_application.yml, config/locales/simple_form.en.yml, db/migrate/20200605023515_add_calendly_to_nonprofit_interest_form.rb, db/schema.rb
Added a new field for signing up for Calendly and added a confirmation email after submitting interest form (copy is tbd)
=> Calendly Field + Confirmation Email

app/views/nonprofit_applications/index.html.slim
=> Quick Application Copy Fix

Gemfile, Gemfile.lock, README.md, app/assets/stylesheets/components/_form.scss, app/controllers/nonprofit_applications_controller.rb, app/models/nonprofit_interest_form.rb, app/validators/http_url_validator.rb, app/views/nonprofit_interest_forms/new.html.slim, app/views/projects/index.html.slim, config/locales/en/members.yml, config/locales/en/nonprofit_interest_forms.yml, config/locales/en/projects.yml, config/locales/simple_form.en.yml, lib/tasks/npo.rake
- Add validation to NPO interest form
- phone number
- website URL
- location present
- Warning when they didn't click Calendly to schedule call
- Change unauth page to NPO sign in instead of sign up
- Other minor changes
- DC project site to documentation site
- Update member list
=> Add validation to NPO interest form

app/controllers/nonprofit_applications_controller.rb, app/decorators/nonprofit_application_decorator.rb, app/models/nonprofit_application.rb, app/views/nonprofit_applications/edit.html.slim, config/locales/simple_form.en.yml, db/schema.rb, lib/tasks/npo.rake, spec/factories/nonprofit_applications.rb, spec/features/new_nonprofit_application_spec.rb, spec/models/nonprofit_application_spec.rb
Added new question to NPO Application part 2 (& a few other small changes):
=> Update Application Part 2 with new question

app/controllers/nonprofit_applications_controller.rb, app/decorators/nonprofit_application_decorator.rb, app/models/nonprofit_application.rb, app/views/nonprofit_applications/edit.html.slim, config/locales/simple_form.en.yml, db/migrate/20200615042111_add_inclusivity_to_nonprofit_applications.rb, db/schema.rb, lib/tasks/npo.rake, spec/factories/nonprofit_applications.rb, spec/features/new_nonprofit_application_spec.rb, spec/models/nonprofit_application_spec.rb
Haha go Presidents
Added NPO inclusivity migration file
=> Alivant/Update App Pt2

app/models/nonprofit_interest_form.rb, app/views/nonprofit_interest_forms/new.html.slim, bin/setup, config/locales/en/members.yml
* Update Peter's former role to VP Projects
* Update setup script to have more conditions
* Update NPO interest form to make Calendly checkbox optional and remove checkbox
=> Minor updates to members page, setup script, and NPO interest form

app/decorators/nonprofit_application_decorator.rb
This lets you view full NPO apps in the app, allows for easy copying to notion, etc.
=> Fixed Admin page for viewing all NPO Applications

app/assets/javascripts/pages/nonprofit_application/save_application.js
Make it clear that NPO as not submitted application when the save button is clicked
=> Minor change to NPO application save toast

config/locales/en/members.yml
Hello Dr. Sauce,
Please consider my changes adding my LinkedIN and website to the members page.
Thank you,
Dr. Butter
=> Add linkedin and website to Nick Wong's record

config/locales/en/members.yml, db/seeds/questions.yml
- Adding new members to our website and Paws Up! 
- Verify members and roles. Please thread here if there's anything that needs to be changed! 
- Gravatars to be uploaded for new members! Need them to use their @berkeley.edu emails.
=> Add new members

config/locales/en/apply/student.yml, config/locales/en/members.yml, config/locales/en/student_application.yml
- updates external members roles
- fixes tinyurl quadripple w's
=> sp2021 updates -- updates roles for memebers

config/locales/en/members.yml
=> adds linkedin for external vp

app/models/student_application.rb
- filters out additional field when viewing student application
=> filter additional field on student applicant view

config/locales/en/members.yml
Adds new developers + (x)ternal members + Fred + Alison :)
=> SP21 - Welcome to Blueprint - New Devs, External + Fred + Alison

CONTRACT.md, app/views/nonprofit_applications/index.html.slim, app/views/nonprofit_interest_forms/new.html.slim, app/views/pages/contract.html.slim, config/locales/en/nonprofit_interest_forms.yml
- Updated Terms of Work
- Updated Interested Form
- Updated Calendly link
=> Update for NPO Recruitment 2021

config/locales/en/members.yml
- This PR updates e-team membership with the current elected leadership
- Adds two new roles - project manager and technical lead
- Replaces Project leader title with Project manager
- Changes titles of active members with Project Leader title to Project Developer as a stand-in while roles are finalized for the fall
- changes active members to default mentor if a role has not been confirmed or their status has not been confirmed
- Tested locally (screenshot below)
One day we won't need to look at slim files *looks into the distance*...
For this PR I modified the `members.yml` -- the `members.yml` file is used in the `about.html.slim` file where it will parse through the `members` section of the `memebers.yml` and render them.
Code snippet of where members are iterated in `about.html.slim` …
=> refactor(members roster): updates e-team membership, adds project manager and technical lead titles

app/views/apply/students.html.slim, config/locales/en/apply/student.yml
- make changes to the event dates and links
=> Make initial changes for member recruitment fall 2021

app/controllers/demographic_surveys_controller.rb, app/models/demographic_survey.rb, app/views/demographic_surveys/new.html.slim, bin/setup, config/locales/en/demographic_survey.yml, db/migrate/20210903065217_add_decline_si_to_demographic_survey.rb, db/schema.rb, lib/tasks/demographics.rake, lib/tasks/students.rake
- Update sync to Airtable for student applications for Fall 2021
- Update demographic survey sync to Airtable for added fields from Spring 2021
- Updated setup script to include seeding of student application questions, application template, and ethnicities for demographic survey
=> Update syncing for student applications Fall 2021 and demographic surveys

app/assets/stylesheets/admin/layout.scss, app/controllers/admins/student_applications_controller.rb, app/models/ability.rb, app/models/student_application.rb, app/views/admins/student_applications/details.html.slim, app/views/admins/student_applications/index.html.slim, app/views/admins/student_applications/show.html.slim, app/views/application/_navbar.html.slim, config/routes.rb
- Embed Airtable form to application page
- Update shown fields in app reading
- Add new page for app details which holds all the fields
- Remove comparisons for student reviewers
=> Update student applications reading

config/locales/en/members.yml
Quick commit to test my setup: updated the member roles as of info we have on 1/15/23.
Updated `/about` page:
=> Update sp23 member roles

app/views/student_applications/new.html.slim, config/locales/en/student_application.yml, db/seeds/applications.yml, db/seeds/questions.yml, lib/tasks/students.rake
- Added sp23 application questions
- Updated relevant due dates
To review:
- Thorough proofreading + making sure this aligns with the final versions e-team decided. I made a couple ad-hoc tweaks, but feel free to suggest changes here if you disagree with anything.
=> [sp23 mem recruit] add spring 2023 application questions

config/locales/chapters.yml
Changes the blurb to be up-to-date with Blueprint Boulder's current status. Solves issue #472
=> Update chapters.yml with new Boulder info

config/locales/en/members.yml
Added all of our new members for the Fall 2023 semester to the website and updated all current members to their current roles.
=> Update website with Fa23 new members

app/views/student_applications/new.html.slim, config/locales/en/apply/student.yml, config/locales/en/student_application.yml
* updates copy for spring '24 recruitment
=> [Spring 2024 Member Recruitment] Updates site copy for sp24

config/locales/en/members.yml
- updates roles for spring 2024, adds new members
=> chore(sp24): update members

app/views/student_applications/new.html.slim, config/locales/en/apply/student.yml
- Change the dates on the /apply and /apply/students pages
=> [fa24-students] update copy for student recruitment

app/views/apply/nonprofits.html.slim, app/views/apply/students.html.slim, config/locales/en/apply/nonprofit.yml
- Added the external airtable link to the website to remove local database dependency.
- [temporary] Remove broken news letter sign up.
=> [fa24-students] add application airtable link to website

config/locales/en/members.yml
- Update website with new member descriptions.
- Move graduated members to alumni status.
=> [roster-fa24] update website roster with new members and roles.
